version: '3'

services:
  server:
    build: server
    volumes:
      - ./public:/app/public
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/server/node_modules
    ports:
      - '80:80'
      - '1234:1234'
    restart: always